name: Sync Fork

on:
  schedule:
    # 每天凌晨 2 点执行同步任务
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "e8732"
          git config user.email "e8732master@gmail.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/fanmingming/live.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes
        run: git push origin main
